import { FileGenerator, GeneratorContext } from './FileGenerator';

export class ClaudeMdGenerator implements FileGenerator {
    async generate(context: GeneratorContext): Promise<string> {
        const parts: string[] = [];

        // Header
        parts.push('# Project Context (CLAUDE.md)');
        parts.push('This file is auto-generated by Align Agents. Do not edit manually.');
        parts.push('');

        // Rules Section
        if (context.rules.length > 0) {
            parts.push('## Active Rules');
            context.rules.forEach(rule => {
                parts.push(`### ${rule.name || rule.content.substring(0, 50)}...`);
                parts.push(rule.content);
                parts.push('');
            });
        }

        // MCP Servers Section
        if (context.mcpServers.length > 0) {
            parts.push('## Active MCP Servers');
            context.mcpServers.forEach(server => {
                if (!server.isActive) return;
                parts.push(`### ${server.name}`);
                parts.push(`- Command: \`${server.command} ${server.args.join(' ')}\``);
                /* 
                   Note: Actual MCP tool definitions would ideally be listed here if we fetched them via listTools(),
                   but purely based on configuration, we list the server command.
                   For full context, we might want to append the JSON config structure if that's what the user wants,
                   but CLAUDE.md is usually text.
                */
                parts.push('');
            });
        }

        return parts.join('\n');
    }
}
